version: "2"
services:

  builder:
    image: openlmis/dev:5.2
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'

  image:
    build: .
    image: openlmis/one-network-stockmanagement-extension-config
